sudo: false

addons:
  apt:
    sources:
    - git-core
    packages:
    - git # needs modern enough git to pass tests

language: go

go:
  - 1.10
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -d github.com/libgit2/git2go

install:
  - (cd $(go env GOPATH)/src/github.com/libgit2/git2go && ./script/build-libgit2-static.sh)
  - go get -tags static -t -v ./...

script:
  - go test -tags static -v -check.v -race ./...

after_success:
  - test "$TRAVIS_GO_VERSION" = "1.10" && goveralls -service=travis-ci
